export const Data = [
  {
    id: 1,
    title: "Web Developer",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi nisi sapiente ducimus repudiandae, aliquid porro sunt. Culpa dolore eos id! Minima veritatis atque quibusdam dicta aperiam iste sunt maiores eum qui! Qui numquam voluptas assumenda, quaerat doloremque natus eveniet ipsum temporibus modi fugiat iure molestias id eos possimus. Iusto explicabo dolor atque qui aperiam magnam vel laudantium quos quidem inventore est nam accusantium, possimus, veritatis maiores molestiae cumque neque praesentium iste doloremque minima earum ipsam sequi obcaecati? Iusto maiores ipsum hic cum, repellat modi corporis, totam veritatis sunt nihil excepturi nemo mollitia, obcaecati recusandae culpa repudiandae amet ex tempore nulla. Animi delectus at praesentium laborum non. Non possimus alias laborum cum sapiente! Rem cupiditate ad tempora vero, consectetur architecto officia iusto recusandae nisi placeat reprehenderit mollitia ipsa aperiam pariatur laudantium eligendi iure tenetur! Quibusdam, nemo error, quidem nisi molestias ipsum facere vero accusamus commodi hic obcaecati necessitatibus deserunt atque enim! Necessitatibus eius laboriosam, maxime illo ea omnis, esse deleniti sit temporibus obcaecati culpa consequuntur tenetur! Laudantium blanditiis iusto cum molestiae ab sunt eligendi, velit quos sed, tenetur omnis vitae obcaecati quia incidunt maxime! Iste ipsum, praesentium assumenda quisquam fuga ut laboriosam corporis consequatur fugit doloribus suscipit, veritatis magni eaque impedit.",
  },
  {
    id: 2,
    title: "Graphic Designer",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi nisi sapiente ducimus repudiandae, aliquid porro sunt. Culpa dolore eos id! Minima veritatis atque quibusdam dicta aperiam iste sunt maiores eum qui! Qui numquam voluptas assumenda, quaerat doloremque natus eveniet ipsum temporibus modi fugiat iure molestias id eos possimus. Iusto explicabo dolor atque qui aperiam magnam vel laudantium quos quidem inventore est nam accusantium, possimus, veritatis maiores molestiae cumque neque praesentium iste doloremque minima earum ipsam sequi obcaecati? Iusto maiores ipsum hic cum, repellat modi corporis, totam veritatis sunt nihil excepturi nemo mollitia, obcaecati recusandae culpa repudiandae amet ex tempore nulla. Animi delectus at praesentium laborum non. Non possimus alias laborum cum sapiente! Rem cupiditate ad tempora vero, consectetur architecto officia iusto recusandae nisi placeat reprehenderit mollitia ipsa aperiam pariatur laudantium eligendi iure tenetur! Quibusdam, nemo error, quidem nisi molestias ipsum facere vero accusamus commodi hic obcaecati necessitatibus deserunt atque enim! Necessitatibus eius laboriosam, maxime illo ea omnis, esse deleniti sit temporibus obcaecati culpa consequuntur tenetur! Laudantium blanditiis iusto cum molestiae ab sunt eligendi, velit quos sed, tenetur omnis vitae obcaecati quia incidunt maxime! Iste ipsum, praesentium assumenda quisquam fuga ut laboriosam corporis consequatur fugit doloribus suscipit, veritatis magni eaque impedit.",
  },
  {
    id: 3,
    title: "Data Analytics Expert",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi nisi sapiente ducimus repudiandae, aliquid porro sunt. Culpa dolore eos id! Minima veritatis atque quibusdam dicta aperiam iste sunt maiores eum qui! Qui numquam voluptas assumenda, quaerat doloremque natus eveniet ipsum temporibus modi fugiat iure molestias id eos possimus. Iusto explicabo dolor atque qui aperiam magnam vel laudantium quos quidem inventore est nam accusantium, possimus, veritatis maiores molestiae cumque neque praesentium iste doloremque minima earum ipsam sequi obcaecati? Iusto maiores ipsum hic cum, repellat modi corporis, totam veritatis sunt nihil excepturi nemo mollitia, obcaecati recusandae culpa repudiandae amet ex tempore nulla. Animi delectus at praesentium laborum non. Non possimus alias laborum cum sapiente! Rem cupiditate ad tempora vero, consectetur architecto officia iusto recusandae nisi placeat reprehenderit mollitia ipsa aperiam pariatur laudantium eligendi iure tenetur! Quibusdam, nemo error, quidem nisi molestias ipsum facere vero accusamus commodi hic obcaecati necessitatibus deserunt atque enim! Necessitatibus eius laboriosam, maxime illo ea omnis, esse deleniti sit temporibus obcaecati culpa consequuntur tenetur! Laudantium blanditiis iusto cum molestiae ab sunt eligendi, velit quos sed, tenetur omnis vitae obcaecati quia incidunt maxime! Iste ipsum, praesentium assumenda quisquam fuga ut laboriosam corporis consequatur fugit doloribus suscipit, veritatis magni eaque impedit.",
  },
  {
    id: 4,
    title: "SEO Expertr",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi nisi sapiente ducimus repudiandae, aliquid porro sunt. Culpa dolore eos id! Minima veritatis atque quibusdam dicta aperiam iste sunt maiores eum qui! Qui numquam voluptas assumenda, quaerat doloremque natus eveniet ipsum temporibus modi fugiat iure molestias id eos possimus. Iusto explicabo dolor atque qui aperiam magnam vel laudantium quos quidem inventore est nam accusantium, possimus, veritatis maiores molestiae cumque neque praesentium iste doloremque minima earum ipsam sequi obcaecati? Iusto maiores ipsum hic cum, repellat modi corporis, totam veritatis sunt nihil excepturi nemo mollitia, obcaecati recusandae culpa repudiandae amet ex tempore nulla. Animi delectus at praesentium laborum non. Non possimus alias laborum cum sapiente! Rem cupiditate ad tempora vero, consectetur architecto officia iusto recusandae nisi placeat reprehenderit mollitia ipsa aperiam pariatur laudantium eligendi iure tenetur! Quibusdam, nemo error, quidem nisi molestias ipsum facere vero accusamus commodi hic obcaecati necessitatibus deserunt atque enim! Necessitatibus eius laboriosam, maxime illo ea omnis, esse deleniti sit temporibus obcaecati culpa consequuntur tenetur! Laudantium blanditiis iusto cum molestiae ab sunt eligendi, velit quos sed, tenetur omnis vitae obcaecati quia incidunt maxime! Iste ipsum, praesentium assumenda quisquam fuga ut laboriosam corporis consequatur fugit doloribus suscipit, veritatis magni eaque impedit.",
  },
  {
    id: 5,
    title: "AI Developer",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi nisi sapiente ducimus repudiandae, aliquid porro sunt. Culpa dolore eos id! Minima veritatis atque quibusdam dicta aperiam iste sunt maiores eum qui! Qui numquam voluptas assumenda, quaerat doloremque natus eveniet ipsum temporibus modi fugiat iure molestias id eos possimus. Iusto explicabo dolor atque qui aperiam magnam vel laudantium quos quidem inventore est nam accusantium, possimus, veritatis maiores molestiae cumque neque praesentium iste doloremque minima earum ipsam sequi obcaecati? Iusto maiores ipsum hic cum, repellat modi corporis, totam veritatis sunt nihil excepturi nemo mollitia, obcaecati recusandae culpa repudiandae amet ex tempore nulla. Animi delectus at praesentium laborum non. Non possimus alias laborum cum sapiente! Rem cupiditate ad tempora vero, consectetur architecto officia iusto recusandae nisi placeat reprehenderit mollitia ipsa aperiam pariatur laudantium eligendi iure tenetur! Quibusdam, nemo error, quidem nisi molestias ipsum facere vero accusamus commodi hic obcaecati necessitatibus deserunt atque enim! Necessitatibus eius laboriosam, maxime illo ea omnis, esse deleniti sit temporibus obcaecati culpa consequuntur tenetur! Laudantium blanditiis iusto cum molestiae ab sunt eligendi, velit quos sed, tenetur omnis vitae obcaecati quia incidunt maxime! Iste ipsum, praesentium assumenda quisquam fuga ut laboriosam corporis consequatur fugit doloribus suscipit, veritatis magni eaque impedit.",
  },
];
